const HomePageData = {
  leadingText: 'WHSPR your',
  slides: [
    {
      id: 700,
      introLine: 'jokes',
      title: 'Joke Title',
      soundUrl: 'https://storage.googleapis.com/whspr-sounds/audio/1704992206087.wav',
      categories: ['funny', 'hilarious', 'GoodJoke'],
      user: {
        id: 700,
        profileImgUrl: 'https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/ear.png',
        username: 'User1',
      },
    },
    {
      id: 701,
      introLine: 'short stories',
      title: 'Short Story Title',
      soundUrl: 'https://storage.googleapis.com/whspr-sounds/audio/1704992206087.wav',
      categories: ['timeless', 'interesting', 'GoodStory'],
      user: {
        id: 700,
        profileImgUrl: 'https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/ear.png',
        username: 'User2',
      },
    },
    {
      id: 702,
      introLine: 'theories',
      title: 'New Theory Title',
      soundUrl: 'https://storage.googleapis.com/whspr-sounds/audio/1704992206087.wav',
      categories: ['DidYouKnow', 'smart', 'amazing'],
      user: {
        id: 700,
        profileImgUrl: 'https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/ear.png',
        username: 'User3',
      },
    },
    {
      id: 703,
      introLine: 'drum solos',
      title: 'Drum Solo Title',
      soundUrl: 'https://storage.googleapis.com/whspr-sounds/audio/1704992206087.wav',
      categories: ['SickBeats', 'rad', 'music'],
      user: {
        id: 700,
        profileImgUrl: 'https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/ear.png',
        username: 'User4',
      },
    },
    {
      id: 704,
      introLine: 'hot gossip',
      title: 'Hot Goss Title',
      soundUrl: 'https://storage.googleapis.com/whspr-sounds/audio/1704992206087.wav',
      categories: ['DidYouHear', 'OMG', 'CanYouBelieve'],
      user: {
        id: 700,
        profileImgUrl: 'https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/ear.png',
        username: 'User5',
      },
    },
    {
      id: 705,
      introLine: 'opinions',
      title: 'Opinion Title',
      soundUrl: 'https://storage.googleapis.com/whspr-sounds/audio/1704992206087.wav',
      categories: ['funny', 'hilarious', 'GoodJoke'],
      user: {
        id: 700,
        profileImgUrl: 'https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/ear.png',
        username: 'User6',
      },
    },
    {
      id: 706,
      introLine: 'poetry',
      title: 'Poetry Title',
      soundUrl: 'https://storage.googleapis.com/whspr-sounds/audio/1704992206087.wav',
      categories: ['timeless', 'interesting', 'GoodStory'],
      user: {
        id: 700,
        profileImgUrl: 'https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/ear.png',
        username: 'User7',
      },
    },
    {
      id: 707,
      introLine: 'monologues',
      title: 'Monologue Title',
      soundUrl: 'https://storage.googleapis.com/whspr-sounds/audio/1704992206087.wav',
      categories: ['DidYouKnow', 'smart', 'amazing'],
      user: {
        id: 700,
        profileImgUrl: 'https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/ear.png',
        username: 'User8',
      },
    },
    {
      id: 708,
      introLine: 'songs',
      title: 'Latest Track Title',
      soundUrl: 'https://storage.googleapis.com/whspr-sounds/audio/1704992206087.wav',
      categories: ['SickBeats', 'rad', 'music'],
      user: {
        id: 700,
        profileImgUrl: 'https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/ear.png',
        username: 'User9',
      },
    },
    {
      id: 709,
      introLine: 'ASMR',
      title: 'ASMR Title',
      soundUrl: 'https://storage.googleapis.com/whspr-sounds/audio/1704992206087.wav',
      categories: ['DidYouHear', 'OMG', 'CanYouBelieve'],
      user: {
        id: 700,
        profileImgUrl: 'https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/ear.png',
        username: 'User10',
      },
    },
  ] };
export default HomePageData;